/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-02-10 21:48:20 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@123.207.28.107/moshi -t account -t account_l -t account_m -t account_role -t account_role_l -t account_role_m -t account_role_t -t account_t -t application -t application_l -t application_m -t application_t -t article -t article_comment -t article_comment_l -t article_comment_m -t article_comment_t -t article_l -t article_m -t article_t -t audio -t audio_l -t audio_m -t audio_t -t auth_code -t auth_code_l -t auth_code_m -t auth_code_t -t course -t course_l -t course_m -t course_t -t issue -t issue_comment -t issue_comment_l -t issue_comment_m -t issue_comment_t -t issue_l -t issue_m -t issue_t -t news -t news_l -t news_m -t news_t -t paragraph -t paragraph_comment -t paragraph_comment_l -t paragraph_comment_m -t paragraph_comment_t -t paragraph_l -t paragraph_m -t paragraph_t -t permission -t permission_l -t permission_m -t permission_t -t preset_text -t preset_text_l -t preset_text_m -t preset_text_t -t recommend -t recommend_l -t recommend_m -t recommend_t -t role -t role_l -t role_m -t role_permission -t role_permission_l -t role_permission_m -t role_permission_t -t role_t -t section -t section_l -t section_m -t section_t -t session -t session_l -t session_m -t session_t -t subscription -t subscription_l -t subscription_m -t subscription_t -t video -t video_l -t video_m -t video_t -s moshi
 *
 */


export interface _IAccount {
    id: number;
    nickName: string;
    password: string;
    email: string;
    phone?: string;
    avatar: string;
    realName?: string;
    identityNumber?: string;
    age?: number;
    company?: string;
    position?: string;
    personalProfile?: string;
    sex?: string;
    birthday?: number;
    education?: string;
    profession?: string;
    createAt: number;
    status: number;
    realPicture?: string;

}

export interface _IAccountL {
    id: number;
    nickName: string;
    password: string;
    email: string;
    phone?: string;
    avatar: string;
    realName?: string;
    identityNumber?: string;
    age?: number;
    company?: string;
    position?: string;
    personalProfile?: string;
    sex?: string;
    birthday?: number;
    education?: string;
    profession?: string;
    createAt: number;
    status: number;
    realPicture?: string;

}

export interface _IAccountM {
    id: number;
    nickName: string;
    password: string;
    email: string;
    phone?: string;
    avatar: string;
    realName?: string;
    identityNumber?: string;
    age?: number;
    company?: string;
    position?: string;
    personalProfile?: string;
    sex?: string;
    birthday?: number;
    education?: string;
    profession?: string;
    createAt: number;
    status: number;
    realPicture?: string;

}

export interface _IAccountRole {
    accountId: number;
    roleId: number;

}

export interface _IAccountRoleL {
    accountId: number;
    roleId: number;

}

export interface _IAccountRoleM {
    accountId: number;
    roleId: number;

}

export interface _IAccountRoleT {
    accountId: number;
    roleId: number;

}

export interface _IAccountT {
    id: number;
    nickName: string;
    password: string;
    email: string;
    phone?: string;
    avatar: string;
    realName?: string;
    identityNumber?: string;
    age?: number;
    company?: string;
    position?: string;
    personalProfile?: string;
    sex?: string;
    birthday?: number;
    education?: string;
    profession?: string;
    createAt: number;
    status: number;
    realPicture?: string;

}

export interface _IApplication {
    id: number;
    accountId: number;
    category: number;
    title: string;
    content: string;
    createAt: number;
    status: number;
    reply?: string;
    refId: number;
    contentType: string;

}

export interface _IApplicationL {
    id: number;
    accountId: number;
    category: number;
    title: string;
    content: string;
    createAt: number;
    status: number;
    reply?: string;
    refId: number;
    contentType: string;

}

export interface _IApplicationM {
    id: number;
    accountId: number;
    category: number;
    title: string;
    content: string;
    createAt: number;
    status: number;
    reply?: string;
    refId: number;
    contentType: string;

}

export interface _IApplicationT {
    id: number;
    accountId: number;
    category: number;
    title: string;
    content: string;
    createAt: number;
    status: number;
    reply?: string;
    refId: number;
    contentType: string;

}

export interface _IArticle {
    id: number;
    courseId: number;
    title: string;
    content: string;
    publishAt?: number;
    createAt: number;
    status: number;
    audioId: number;
    contentType: string;

}

export interface _IArticleComment {
    id: number;
    articleId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface _IArticleCommentL {
    id: number;
    articleId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface _IArticleCommentM {
    id: number;
    articleId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface _IArticleCommentT {
    id: number;
    articleId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface _IArticleL {
    id: number;
    courseId: number;
    title: string;
    content: string;
    publishAt?: number;
    createAt: number;
    status: number;
    audioId: number;
    contentType: string;

}

export interface _IArticleM {
    id: number;
    courseId: number;
    title: string;
    content: string;
    publishAt?: number;
    createAt: number;
    status: number;
    audioId: number;
    contentType: string;

}

export interface _IArticleT {
    id: number;
    courseId: number;
    title: string;
    content: string;
    publishAt?: number;
    createAt: number;
    status: number;
    audioId: number;
    contentType: string;

}

export interface _IAudio {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;
    name: string;
    uploadAt: number;

}

export interface _IAudioL {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;
    name: string;
    uploadAt: number;

}

export interface _IAudioM {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;
    name: string;
    uploadAt: number;

}

export interface _IAudioT {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;
    name: string;
    uploadAt: number;

}

export interface _IAuthCode {
    id: string;
    accountId: number;
    expireAt: number;
    type: number;

}

export interface _IAuthCodeL {
    id: string;
    accountId: number;
    expireAt: number;
    type: number;

}

export interface _IAuthCodeM {
    id: string;
    accountId: number;
    expireAt: number;
    type: number;

}

export interface _IAuthCodeT {
    id: string;
    accountId: number;
    expireAt: number;
    type: number;

}

export interface _ICourse {
    id: number;
    accountId: number;
    name: string;
    introduce: string;
    introduceImage?: string;
    note?: string;
    createAt: number;
    publishAt?: number;
    buyerCount: number;
    courseType: number;
    price?: number;
    discountedPrice?: number;
    offerTo?: number;
    status: number;
    lectureCount: number;

}

export interface _ICourseL {
    id: number;
    accountId: number;
    name: string;
    introduce: string;
    introduceImage?: string;
    note?: string;
    createAt: number;
    publishAt?: number;
    buyerCount: number;
    courseType: number;
    price?: number;
    discountedPrice?: number;
    offerTo?: number;
    status: number;
    lectureCount: number;

}

export interface _ICourseM {
    id: number;
    accountId: number;
    name: string;
    introduce: string;
    introduceImage?: string;
    note?: string;
    createAt: number;
    publishAt?: number;
    buyerCount: number;
    courseType: number;
    price?: number;
    discountedPrice?: number;
    offerTo?: number;
    status: number;
    lectureCount: number;

}

export interface _ICourseT {
    id: number;
    accountId: number;
    name: string;
    introduce: string;
    introduceImage?: string;
    note?: string;
    createAt: number;
    publishAt?: number;
    buyerCount: number;
    courseType: number;
    price?: number;
    discountedPrice?: number;
    offerTo?: number;
    status: number;
    lectureCount: number;

}

export interface _IIssue {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    openAt: number;
    closerId?: number;
    closeAt?: number;
    status: number;

}

export interface _IIssueComment {
    id: number;
    issueId: number;
    accountId: number;
    createAt: number;
    content: string;
    status: number;

}

export interface _IIssueCommentL {
    id: number;
    issueId: number;
    accountId: number;
    createAt: number;
    content: string;
    status: number;

}

export interface _IIssueCommentM {
    id: number;
    issueId: number;
    accountId: number;
    createAt: number;
    content: string;
    status: number;

}

export interface _IIssueCommentT {
    id: number;
    issueId: number;
    accountId: number;
    createAt: number;
    content: string;
    status: number;

}

export interface _IIssueL {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    openAt: number;
    closerId?: number;
    closeAt?: number;
    status: number;

}

export interface _IIssueM {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    openAt: number;
    closerId?: number;
    closeAt?: number;
    status: number;

}

export interface _IIssueT {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    openAt: number;
    closerId?: number;
    closeAt?: number;
    status: number;

}

export interface _INews {
    id: number;
    title: string;
    content: string;
    createAt: number;
    publishAt?: number;
    status: number;
    author: string;
    audioId?: number;
    contentType: string;

}

export interface _INewsL {
    id: number;
    title: string;
    content: string;
    createAt: number;
    publishAt?: number;
    status: number;
    author: string;
    audioId?: number;
    contentType: string;

}

export interface _INewsM {
    id: number;
    title: string;
    content: string;
    createAt: number;
    publishAt?: number;
    status: number;
    author: string;
    audioId?: number;
    contentType: string;

}

export interface _INewsT {
    id: number;
    title: string;
    content: string;
    createAt: number;
    publishAt?: number;
    status: number;
    author: string;
    audioId?: number;
    contentType: string;

}

export interface _IParagraph {
    id: number;
    sectionId: number;
    accountId: number;
    vedioId: number;
    content: string;
    createAt: number;
    status: number;

}

export interface _IParagraphComment {
    id: number;
    paragraphId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface _IParagraphCommentL {
    id: number;
    paragraphId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface _IParagraphCommentM {
    id: number;
    paragraphId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface _IParagraphCommentT {
    id: number;
    paragraphId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface _IParagraphL {
    id: number;
    sectionId: number;
    accountId: number;
    vedioId: number;
    content: string;
    createAt: number;
    status: number;

}

export interface _IParagraphM {
    id: number;
    sectionId: number;
    accountId: number;
    vedioId: number;
    content: string;
    createAt: number;
    status: number;

}

export interface _IParagraphT {
    id: number;
    sectionId: number;
    accountId: number;
    vedioId: number;
    content: string;
    createAt: number;
    status: number;

}

export interface _IPermission {
    id: number;
    actionKey: string;
    controller: string;
    remark?: string;

}

export interface _IPermissionL {
    id: number;
    actionKey: string;
    controller: string;
    remark?: string;

}

export interface _IPermissionM {
    id: number;
    actionKey: string;
    controller: string;
    remark?: string;

}

export interface _IPermissionT {
    id: number;
    actionKey: string;
    controller: string;
    remark?: string;

}

export interface _IPresetText {
    key: string;
    value: string;
    type: string;

}

export interface _IPresetTextL {
    key: string;
    value: string;
    type: string;

}

export interface _IPresetTextM {
    key: string;
    value: string;
    type: string;

}

export interface _IPresetTextT {
    key: string;
    value: string;
    type: string;

}

export interface _IRecommend {
    id: number;
    image: string;
    title: string;
    content: string;
    createAt: number;
    status: number;
    contentType: string;

}

export interface _IRecommendL {
    id: number;
    image: string;
    title: string;
    content: string;
    createAt: number;
    status: number;
    contentType: string;

}

export interface _IRecommendM {
    id: number;
    image: string;
    title: string;
    content: string;
    createAt: number;
    status: number;
    contentType: string;

}

export interface _IRecommendT {
    id: number;
    image: string;
    title: string;
    content: string;
    createAt: number;
    status: number;
    contentType: string;

}

export interface _IRole {
    id: number;
    name: string;
    createAt: number;

}

export interface _IRoleL {
    id: number;
    name: string;
    createAt: number;

}

export interface _IRoleM {
    id: number;
    name: string;
    createAt: number;

}

export interface _IRolePermission {
    roleId: number;
    permissionId: number;

}

export interface _IRolePermissionL {
    roleId: number;
    permissionId: number;

}

export interface _IRolePermissionM {
    roleId: number;
    permissionId: number;

}

export interface _IRolePermissionT {
    roleId: number;
    permissionId: number;

}

export interface _IRoleT {
    id: number;
    name: string;
    createAt: number;

}

export interface _ISection {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    createAt: number;
    status: number;

}

export interface _ISectionL {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    createAt: number;
    status: number;

}

export interface _ISectionM {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    createAt: number;
    status: number;

}

export interface _ISectionT {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    createAt: number;
    status: number;

}

export interface _ISession {
    id: string;
    accountId: number;
    expireAt: number;

}

export interface _ISessionL {
    id: string;
    accountId: number;
    expireAt: number;

}

export interface _ISessionM {
    id: string;
    accountId: number;
    expireAt: number;

}

export interface _ISessionT {
    id: string;
    accountId: number;
    expireAt: number;

}

export interface _ISubscription {
    id: number;
    accountId: number;
    refId: number;
    subscribeType: string;
    createAt: number;
    cost: number;
    status: number;

}

export interface _ISubscriptionL {
    id: number;
    accountId: number;
    refId: number;
    subscribeType: string;
    createAt: number;
    cost: number;
    status: number;

}

export interface _ISubscriptionM {
    id: number;
    accountId: number;
    refId: number;
    subscribeType: string;
    createAt: number;
    cost: number;
    status: number;

}

export interface _ISubscriptionT {
    id: number;
    accountId: number;
    refId: number;
    subscribeType: string;
    createAt: number;
    cost: number;
    status: number;

}

export interface _IVideo {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;
    name: string;
    uploadAt: number;

}

export interface _IVideoL {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;
    name: string;
    uploadAt: number;

}

export interface _IVideoM {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;
    name: string;
    uploadAt: number;

}

export interface _IVideoT {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;
    name: string;
    uploadAt: number;

}
